apiVersion: v1
kind: Service
metadata:
  name: myapp-nosql
  labels:
    app: myapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
    tier: nosql
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nosql-pv-claim
  labels:
    app: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-nosql
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      tier: nosql
  serviceName: nosql
  template:
    metadata:
      labels:
        app: myapp
        tier: nosql
    spec:
      containers:
      - name: nosql
        image: iad.ocir.io/oradbclouducm/nosqldemos/oracle/nosql:ce
        imagePullPolicy: Always        
        env:
        - name: KV_PROXY_PORT
          value: "80"
        ports:
        - containerPort: 80
          name: nosql
        volumeMounts:
        - name: nosql-persistent-storage
          mountPath: /kvroot
      volumes:
      - name: nosql-persistent-storage
        persistentVolumeClaim:
          claimName: nosql-pv-claim
      imagePullSecrets:
      - name: ocirsecret
